
export const GET_ACTIONSKRI_REQUEST = 'GET_ACTIONSKRI_REQUEST';
export const GET_ACTIONSKRI_SUCCESS = 'GET_ACTIONSKRI_SUCCESS';
export const GET_ACTIONSKRI_FAILED = 'GET_ACTIONSKRI_FAILED';

export const UPDATE_ACTIONKRI_REQUEST = 'UPDATE_ACTIONKRI_REQUEST';
export const UPDATE_ACTIONKRI_SUCCESS = 'UPDATE_ACTIONKRI_SUCCESS';
export const UPDATE_ACTIONKRI_FAILED = 'UPDATE_ACTIONKRI_FAILED';

export const ADD_ACTIONKRI_REQUEST = 'ADD_ACTIONKRI_REQUEST';
export const ADD_ACTIONKRI_SUCCESS = 'ADD_ACTIONKRI_SUCCESS';
export const ADD_ACTIONKRI_FAILED = 'ADD_ACTIONKRI_FAILED';

export const DELETE_ACTIONKRI_REQUEST = 'DELETE_ACTIONKRI_REQUEST';
export const DELETE_ACTIONKRI_SUCCESS = 'DELETE_ACTIONKRI_SUCCESS';
export const DELETE_ACTIONKRI_FAILED = 'DELETE_ACTIONKRI_FAILED';

export const GET_ACTIONKRI_REQUEST = 'GET_ACTIONKRI_REQUEST';
export const GET_ACTIONKRI_SUCCESS = 'GET_ACTIONKRI_SUCCESS';
export const GET_ACTIONKRI_FAILED = 'GET_ACTIONKRI_FAILED';