
export const GET_ALL_ACTIONS_REQUEST = 'GET_ALL_ACTIONS_REQUEST';
export const GET_ALL_ACTIONS_SUCCESS = 'GET_ALL_ACTIONS_SUCCESS';
export const GET_ALL_ACTIONS_FAILED = 'GET_ALL_ACTIONS_FAILED';

export const GET_ACTIONS_REQUEST = 'GET_ACTIONS_REQUEST';
export const GET_ACTIONS_SUCCESS = 'GET_ACTIONS_SUCCESS';
export const GET_ACTIONS_FAILED = 'GET_ACTIONS_FAILED';

export const GET_ENTITY_ACTIONS_REQUEST = 'GET_ENTITY_ACTIONS_REQUEST';
export const GET_ENTITY_ACTIONS_SUCCESS = 'GET_ENTITY_ACTIONS_SUCCESS';
export const GET_ENTITY_ACTIONS_FAILED = 'GET_ENTITY_ACTIONS_FAILED';

export const UPDATE_ACTION_REQUEST = 'UPDATE_ACTION_REQUEST';
export const UPDATE_ACTION_SUCCESS = 'UPDATE_ACTION_SUCCESS';
export const UPDATE_ACTION_FAILED = 'UPDATE_ACTION_FAILED';

export const ADD_ACTION_REQUEST = 'ADD_ACTION_REQUEST';
export const ADD_ACTION_SUCCESS = 'ADD_ACTION_SUCCESS';
export const ADD_ACTION_FAILED = 'ADD_ACTION_FAILED';

export const DELETE_ACTION_REQUEST = 'DELETE_ACTION_REQUEST';
export const DELETE_ACTION_SUCCESS = 'DELETE_ACTION_SUCCESS';
export const DELETE_ACTION_FAILED = 'DELETE_ACTION_FAILED';