
export const GET_ALL_KRI_REQUEST = 'GET_ALL_KRI_REQUEST';
export const GET_ALL_KRI_SUCCESS = 'GET_ALL_KRI_SUCCESS';
export const GET_ALL_KRI_FAILED = 'GET_ALL_KRI_FAILED';

export const GET_KRI_REQUEST = 'GET_KRI_REQUEST';
export const GET_KRI_SUCCESS = 'GET_KRI_SUCCESS';
export const GET_KRI_FAILED = 'GET_KRI_FAILED';

export const GET_ENTITY_KRI_REQUEST = 'GET_ENTITY_KRI_REQUEST';
export const GET_ENTITY_KRI_SUCCESS = 'GET_ENTITY_KRI_SUCCESS';
export const GET_ENTITY_KRI_FAILED = 'GET_ENTITY_KRI_FAILED';

export const UPDATE_KRI_REQUEST = 'UPDATE_KRI_REQUEST';
export const UPDATE_KRI_SUCCESS = 'UPDATE_KRI_SUCCESS';
export const UPDATE_KRI_FAILED = 'UPDATE_KRI_FAILED';

export const ADD_KRI_REQUEST = 'ADD_KRI_REQUEST';
export const ADD_KRI_SUCCESS = 'ADD_KRI_SUCCESS';
export const ADD_KRI_FAILED = 'ADD_KRI_FAILED';

export const DELETE_KRI_REQUEST = 'DELETE_KRI_REQUEST';
export const DELETE_KRI_SUCCESS = 'DELETE_KRI_SUCCESS';
export const DELETE_KRI_FAILED = 'DELETE_KRI_FAILED';