
export const GET_CONTROLHISTORIES_REQUEST = 'GET_CONTROLHISTORIES_REQUEST';
export const GET_CONTROLHISTORIES_SUCCESS = 'GET_CONTROLHISTORIES_SUCCESS';
export const GET_CONTROLHISTORIES_FAILED = 'GET_CONTROLHISTORIES_FAILED';

export const UPDATE_CONTROLHISTORY_REQUEST = 'UPDATE_CONTROLHISTORY_REQUEST';
export const UPDATE_CONTROLHISTORY_SUCCESS = 'UPDATE_CONTROLHISTORY_SUCCESS';
export const UPDATE_CONTROLHISTORY_FAILED = 'UPDATE_CONTROLHISTORY_FAILED';

export const ADD_CONTROLHISTORY_REQUEST = 'ADD_CONTROLHISTORY_REQUEST';
export const ADD_CONTROLHISTORY_SUCCESS = 'ADD_CONTROLHISTORY_SUCCESS';
export const ADD_CONTROLHISTORY_FAILED = 'ADD_CONTROLHISTORY_FAILED';

export const DELETE_CONTROLHISTORY_REQUEST = 'DELETE_CONTROLHISTORY_REQUEST';
export const DELETE_CONTROLHISTORY_SUCCESS = 'DELETE_CONTROLHISTORY_SUCCESS';
export const DELETE_CONTROLHISTORY_FAILED = 'DELETE_CONTROLHISTORY_FAILED';

export const GET_CONTROLHISTORY_REQUEST = 'GET_CONTROLHISTORY_REQUEST';
export const GET_CONTROLHISTORY_SUCCESS = 'GET_CONTROLHISTORY_SUCCESS';
export const GET_CONTROLHISTORY_FAILED = 'GET_CONTROLHISTORY_FAILED';