
export const GET_ENTITIES_REQUEST = 'GET_ENTITIES_REQUEST';
export const GET_ENTITIES_SUCCESS = 'GET_ENTITIES_SUCCESS';
export const GET_ENTITIES_FAILED = 'GET_ENTITIES_FAILED';

export const UPDATE_ENTITY_REQUEST = 'UPDATE_ENTITY_REQUEST';
export const UPDATE_ENTITY_SUCCESS = 'UPDATE_ENTITY_SUCCESS';
export const UPDATE_ENTITY_FAILED = 'UPDATE_ENTITY_FAILED';

export const ADD_ENTITY_REQUEST = 'ADD_ENTITY_REQUEST';
export const ADD_ENTITY_SUCCESS = 'ADD_ENTITY_SUCCESS';
export const ADD_ENTITY_FAILED = 'ADD_ENTITY_FAILED';

export const DELETE_ENTITY_REQUEST = 'DELETE_ENTITY_REQUEST';
export const DELETE_ENTITY_SUCCESS = 'DELETE_ENTITY_SUCCESS';
export const DELETE_ENTITY_FAILED = 'DELETE_ENTITY_FAILED';

export const GET_ENTITY_REQUEST = 'GET_ENTITY_REQUEST';
export const GET_ENTITY_SUCCESS = 'GET_ENTITY_SUCCESS';
export const GET_ENTITY_FAILED = 'GET_ENTITY_FAILED';