
export const GET_TENANTS_REQUEST = 'GET_TENANTS_REQUEST';
export const GET_TENANTS_SUCCESS = 'GET_TENANTS_SUCCESS';
export const GET_TENANTS_FAILED = 'GET_TENANTS_FAILED';

export const UPDATE_TENANT_REQUEST = 'UPDATE_TENANT_REQUEST';
export const UPDATE_TENANT_SUCCESS = 'UPDATE_TENANT_SUCCESS';
export const UPDATE_TENANT_FAILED = 'UPDATE_TENANT_FAILED';

export const ADD_TENANT_REQUEST = 'ADD_TENANT_REQUEST';
export const ADD_TENANT_SUCCESS = 'ADD_TENANT_SUCCESS';
export const ADD_TENANT_FAILED = 'ADD_TENANT_FAILED';

export const DELETE_TENANT_REQUEST = 'DELETE_TENANT_REQUEST';
export const DELETE_TENANT_SUCCESS = 'DELETE_TENANT_SUCCESS';
export const DELETE_TENANT_FAILED = 'DELETE_TENANT_FAILED';

export const GET_TENANT_REQUEST = 'GET_TENANT_REQUEST';
export const GET_TENANT_SUCCESS = 'GET_TENANT_SUCCESS';
export const GET_TENANT_FAILED = 'GET_TENANT_FAILED';