
export const GET_USERGROUPS_REQUEST = 'GET_USERGROUPS_REQUEST';
export const GET_USERGROUPS_SUCCESS = 'GET_USERGROUPS_SUCCESS';
export const GET_USERGROUPS_FAILED = 'GET_USERGROUPS_FAILED';

export const UPDATE_USERGROUP_REQUEST = 'UPDATE_USERGROUP_REQUEST';
export const UPDATE_USERGROUP_SUCCESS = 'UPDATE_USERGROUP_SUCCESS';
export const UPDATE_USERGROUP_FAILED = 'UPDATE_USERGROUP_FAILED';

export const ADD_USERGROUP_REQUEST = 'ADD_USERGROUP_REQUEST';
export const ADD_USERGROUP_SUCCESS = 'ADD_USERGROUP_SUCCESS';
export const ADD_USERGROUP_FAILED = 'ADD_USERGROUP_FAILED';

export const DELETE_USERGROUP_REQUEST = 'DELETE_USERGROUP_REQUEST';
export const DELETE_USERGROUP_SUCCESS = 'DELETE_USERGROUP_SUCCESS';
export const DELETE_USERGROUP_FAILED = 'DELETE_USERGROUP_FAILED';

export const GET_USERGROUP_REQUEST = 'GET_USERGROUP_REQUEST';
export const GET_USERGROUP_SUCCESS = 'GET_USERGROUP_SUCCESS';
export const GET_USERGROUP_FAILED = 'GET_USERGROUP_FAILED';