
export const GET_ENTITYRISKCONTROLS_REQUEST = 'GET_ENTITYRISKCONTROLS_REQUEST';
export const GET_ENTITYRISKCONTROLS_SUCCESS = 'GET_ENTITYRISKCONTROLS_SUCCESS';
export const GET_ENTITYRISKCONTROLS_FAILED = 'GET_ENTITYRISKCONTROLS_FAILED';

export const UPDATE_ENTITYRISKCONTROL_REQUEST = 'UPDATE_ENTITYRISKCONTROL_REQUEST';
export const UPDATE_ENTITYRISKCONTROL_SUCCESS = 'UPDATE_ENTITYRISKCONTROL_SUCCESS';
export const UPDATE_ENTITYRISKCONTROL_FAILED = 'UPDATE_ENTITYRISKCONTROL_FAILED';

export const ADD_ENTITYRISKCONTROL_REQUEST = 'ADD_ENTITYRISKCONTROL_REQUEST';
export const ADD_ENTITYRISKCONTROL_SUCCESS = 'ADD_ENTITYRISKCONTROL_SUCCESS';
export const ADD_ENTITYRISKCONTROL_FAILED = 'ADD_ENTITYRISKCONTROL_FAILED';

export const DELETE_ENTITYRISKCONTROL_REQUEST = 'DELETE_ENTITYRISKCONTROL_REQUEST';
export const DELETE_ENTITYRISKCONTROL_SUCCESS = 'DELETE_ENTITYRISKCONTROL_SUCCESS';
export const DELETE_ENTITYRISKCONTROL_FAILED = 'DELETE_ENTITYRISKCONTROL_FAILED';

export const GET_ENTITYRISKCONTROL_REQUEST = 'GET_ENTITYRISKCONTROL_REQUEST';
export const GET_ENTITYRISKCONTROL_SUCCESS = 'GET_ENTITYRISKCONTROL_SUCCESS';
export const GET_ENTITYRISKCONTROL_FAILED = 'GET_ENTITYRISKCONTROL_FAILED';

export const COPY_ENTITYRISKCONTROL_REQUEST = 'COPY_ENTITYRISKCONTROL_REQUEST';
export const COPY_ENTITYRISKCONTROL_SUCCESS = 'COPY_ENTITYRISKCONTROL_SUCCESS';
export const COPY_ENTITYRISKCONTROL_FAILED = 'COPY_ENTITYRISKCONTROL_FAILED';

export const MOVE_ENTITYRISKCONTROL_REQUEST = 'MOVE_ENTITYRISKCONTROL_REQUEST';
export const MOVE_ENTITYRISKCONTROL_SUCCESS = 'MOVE_ENTITYRISKCONTROL_SUCCESS';
export const MOVE_ENTITYRISKCONTROL_FAILED = 'MOVE_ENTITYRISKCONTROL_FAILED';