
export const GET_HISTORIESKRI_REQUEST = 'GET_HISTORIESKRI_REQUEST';
export const GET_HISTORIESKRI_SUCCESS = 'GET_HISTORIESKRI_SUCCESS';
export const GET_HISTORIESKRI_FAILED = 'GET_HISTORIESKRI_FAILED';

export const UPDATE_HISTORYKRI_REQUEST = 'UPDATE_HISTORYKRI_REQUEST';
export const UPDATE_HISTORYKRI_SUCCESS = 'UPDATE_HISTORYKRI_SUCCESS';
export const UPDATE_HISTORYKRI_FAILED = 'UPDATE_HISTORYKRI_FAILED';

export const ADD_HISTORYKRI_REQUEST = 'ADD_HISTORYKRI_REQUEST';
export const ADD_HISTORYKRI_SUCCESS = 'ADD_HISTORYKRI_SUCCESS';
export const ADD_HISTORYKRI_FAILED = 'ADD_HISTORYKRI_FAILED';

export const DELETE_HISTORYKRI_REQUEST = 'DELETE_HISTORYKRI_REQUEST';
export const DELETE_HISTORYKRI_SUCCESS = 'DELETE_HISTORYKRI_SUCCESS';
export const DELETE_HISTORYKRI_FAILED = 'DELETE_HISTORYKRI_FAILED';

export const GET_HISTORYKRI_REQUEST = 'GET_HISTORYKRI_REQUEST';
export const GET_HISTORYKRI_SUCCESS = 'GET_HISTORYKRI_SUCCESS';
export const GET_HISTORYKRI_FAILED = 'GET_HISTORYKRI_FAILED';