
export const GET_ALL_REPORTS_REQUEST = 'GET_ALL_REPORTS_REQUEST';
export const GET_ALL_REPORTS_SUCCESS = 'GET_ALL_REPORTS_SUCCESS';
export const GET_ALL_REPORTS_FAILED = 'GET_ALL_REPORTS_FAILED';

export const GET_REPORTS_REQUEST = 'GET_REPORTS_REQUEST';
export const GET_REPORTS_SUCCESS = 'GET_REPORTS_SUCCESS';
export const GET_REPORTS_FAILED = 'GET_REPORTS_FAILED';

export const GET_ENTITY_REPORTS_REQUEST = 'GET_ENTITY_REPORTS_REQUEST';
export const GET_ENTITY_REPORTS_SUCCESS = 'GET_ENTITY_REPORTS_SUCCESS';
export const GET_ENTITY_REPORTS_FAILED = 'GET_ENTITY_REPORTS_FAILED';

export const GET_EVENT_ENTITY_REPORTS_REQUEST = 'GET_EVENT_ENTITY_REPORTS_REQUEST';
export const GET_EVENT_ENTITY_REPORTS_SUCCESS = 'GET_EVENT_ENTITY_REPORTS_SUCCESS';
export const GET_EVENT_ENTITY_REPORTS_FAILED = 'GET_EVENT_ENTITY_REPORTS_FAILED';

export const UPDATE_REPORT_REQUEST = 'UPDATE_REPORT_REQUEST';
export const UPDATE_REPORT_SUCCESS = 'UPDATE_REPORT_SUCCESS';
export const UPDATE_REPORT_FAILED = 'UPDATE_REPORT_FAILED';

export const ADD_REPORT_REQUEST = 'ADD_REPORT_REQUEST';
export const ADD_REPORT_SUCCESS = 'ADD_REPORT_SUCCESS';
export const ADD_REPORT_FAILED = 'ADD_REPORT_FAILED';

export const DELETE_REPORT_REQUEST = 'DELETE_REPORT_REQUEST';
export const DELETE_REPORT_SUCCESS = 'DELETE_REPORT_SUCCESS';
export const DELETE_REPORT_FAILED = 'DELETE_REPORT_FAILED';