
export const GET_RISKCONTROLS_REQUEST = 'GET_RISKCONTROLS_REQUEST';
export const GET_RISKCONTROLS_SUCCESS = 'GET_RISKCONTROLS_SUCCESS';
export const GET_RISKCONTROLS_FAILED = 'GET_RISKCONTROLS_FAILED';

export const UPDATE_RISKCONTROL_REQUEST = 'UPDATE_RISKCONTROL_REQUEST';
export const UPDATE_RISKCONTROL_SUCCESS = 'UPDATE_RISKCONTROL_SUCCESS';
export const UPDATE_RISKCONTROL_FAILED = 'UPDATE_RISKCONTROL_FAILED';

export const ADD_RISKCONTROL_REQUEST = 'ADD_RISKCONTROL_REQUEST';
export const ADD_RISKCONTROL_SUCCESS = 'ADD_RISKCONTROL_SUCCESS';
export const ADD_RISKCONTROL_FAILED = 'ADD_RISKCONTROL_FAILED';

export const DELETE_RISKCONTROL_REQUEST = 'DELETE_RISKCONTROL_REQUEST';
export const DELETE_RISKCONTROL_SUCCESS = 'DELETE_RISKCONTROL_SUCCESS';
export const DELETE_RISKCONTROL_FAILED = 'DELETE_RISKCONTROL_FAILED';

export const GET_RISKCONTROL_REQUEST = 'GET_RISKCONTROL_REQUEST';
export const GET_RISKCONTROL_SUCCESS = 'GET_RISKCONTROL_SUCCESS';
export const GET_RISKCONTROL_FAILED = 'GET_RISKCONTROL_FAILED';